<a href="https://colab.research.google.com/github/myasym/carisurg-portfolio/blob/main/week_0/day_1_gender_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
# Mounting Google Drive so files can be accessed from Colab
from google.colab import drive
drive.mount('/content/drive')

print("Drive mounted successfully.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive mounted successfully.

In [79]:
#Confirming Python version
import sys

print(f"Python version: {sys.version}") # The f prefix tells Python to look for {} placeholders. If no prefix was used, the braces would be ignored

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [80]:
import pandas as pd # Loads the Pandas library, which is used for handling data tables
import numpy as np # Loads the NumPy lirary, which handles high performance mathematical operations and arrays
import matplotlib.pyplot as plt # Loads the Pyplot interface from Matplotlib, which is sed to create graphs and charts

print("Libraries successfully set up.")

Libraries successfully set up.

In [81]:
# Load and inspect dataset
df_raw = pd.read_csv("/content/drive/MyDrive/CariSurg MedTech Pathways 2026/Week 0/Data/EmergencyTriageDataset_Reduced_Dirty.csv")
print(f"Dataset loaded: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns")
print(f"\nColumns: {list(df_raw.columns)}\n")

df_raw.head()

Dataset loaded: 2205 rows x 11 columns
Columns: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0

In [82]:
# Inspect gender column
print("Unique values in Gender:")
print(df_raw['Gender'].unique())
print(f"\nTotal unique values: {df_raw['Gender'].nunique()}")
print("\nGender value counts:")
print(df_raw['Gender'].value_counts())

Unique values in Gender:
['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

Total unique values: 6

Gender value counts:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [83]:
# Build mapping for Gender
gender_map = {
    '1': 1,
    'MALE':1,
    'Male':1,
    'FEMALE':0,
    'Female':0,
    '0':0,
}

# Create new column for cleaned gender data
df_raw['Gender Clean'] = df_raw['Gender'].map(gender_map)

In [84]:
# Verify cleaning
print("After cleaning:")
print(df_raw['Gender Clean'].value_counts())
print(f"\nAny NaN values? {df_raw['Gender'].isnull().sum()}")

After cleaning:
Gender Clean
1    1176
0    1029
Name: count, dtype: int64

Any NaN values? 0

In [85]:
# Drop the original dirty column
df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender Clean': 'Gender'})

# Confirming result
print("Column 'Gender' after cleaning:")
print(df_raw['Gender'].value_counts())
print(f"Data type: {df_raw['Gender'].dtype}")
print(f"\nAny NaN values? {df_raw['Gender'].isnull().sum()}\n")
df_raw.head()

Column 'Gender' after cleaning:
Gender
1    1176
0    1029
Name: count, dtype: int64
Data type: int64

Any NaN values? 0

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0

In [87]:
# Create new cvs file with cleaned Gender column
df_raw.to_csv("/content/drive/MyDrive/CariSurg MedTech Pathways 2026/Week 0/Data/EmergencyTriageDataset_Reduced_Gender_Cleaned.csv", index=False)

📓 Lessons Learnt


- I found that splitting my work into clear steps (loading, inspecting, cleaning, verifying) made my code easier to understand and debug.

- I learnt to always check outputs using .head(), .unique(), and .value_counts() after each change. This helped me confirm everything was working correctly before moving on.

- I realised I should avoid overwriting original columns too early. Keeping a clean version alongside the raw data makes the workflow safer and more flexible.

- When I deleted the 'Gender' column and renamed 'Gender Clean' --> 'Gender', the notebook broke on re-run because the 'Gender' column no longer existed. This showed me that my workflow wasn’t fully  reproducible and idempotent (new word to my vocab, haha!). In future, I would either:
   - keep both the raw and cleaned columns, or
   - maintain an untouched copy of the original dataset and only transform a working copy.